apiVersion: v1
kind: ConfigMap
metadata:
  name: elast-config
  labels:
    app: elastalert
data:
  elastalert_config.yaml: |-
    rules_folder: /opt/rules
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: elasticsearch
    es_port: 9200
    writeback_index: elastalert_status
    alert_time_limit:
      days: 1
  elastalert_alert.yaml: |-
    name: CMS Error
    type: frequency
    index: k8s-*
    num_events: 1
    timeframe:
        minutes: 15
    filter:
    - query:
        wildcard:
          message: "*error*"
    alert:
    - "slack"
    slack:
    # monitor_cms_dev
    slack_webhook_url: "https://hooks.slack.com/services/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"